version: 2
updates:
- package-ecosystem: nuget
  directory: "/Selenium.Axe"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  commit-message:
  ignore:
    # FluentAssertions v6 dropped support for .NET Framework 4.5, but we want
    # to maintain support for it at least until Microsoft drops official support,
    # so we need to pin to FluentAssertions v5 for the time being.
  - dependency-name: FluentAssertions
    versions:
    - ">=6.0.0"
- package-ecosystem: npm
  directory: "/Selenium.Axe/Selenium.Axe"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  commit-message:
